"""
Example Selenium Test Script
Generated by QA Agent - Demonstrates best practices

This is a reference implementation showing how to structure
and run Selenium tests with the generated scripts.
"""

import os
import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import logging
import time


# ==================== Configuration ====================

# Test Configuration
TEST_ID = "TC_EXAMPLE"
TEST_URL = "http://localhost:8080/simple_checkout.html"
IMPLICIT_WAIT = 10  # seconds
EXPLICIT_WAIT = 10  # seconds

# Get configuration from environment variables
HEADLESS = os.getenv('SELENIUM_HEADLESS', 'true').lower() == 'true'
VERBOSE = os.getenv('SELENIUM_VERBOSE', 'false').lower() == 'true'

# Setup logging
logging.basicConfig(
    level=logging.DEBUG if VERBOSE else logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


# ==================== Helper Functions ====================

def setup_driver():
    """Initialize Chrome WebDriver with proper options."""
    logger.info("Setting up Chrome WebDriver...")

    # Chrome options
    options = Options()

    if HEADLESS:
        options.add_argument('--headless')
        logger.info("Running in headless mode")

    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--disable-gpu')
    options.add_argument('--window-size=1920,1080')

    # Use WebDriver Manager to auto-download driver
    try:
        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=options)
        driver.implicitly_wait(IMPLICIT_WAIT)
        logger.info("✅ WebDriver initialized successfully")
        return driver
    except Exception as e:
        logger.error(f"❌ Failed to initialize WebDriver: {e}")
        raise


def wait_for_element(driver, by, value, timeout=EXPLICIT_WAIT):
    """Wait for element to be present and return it."""
    try:
        element = WebDriverWait(driver, timeout).until(
            EC.presence_of_element_located((by, value))
        )
        return element
    except Exception as e:
        logger.error(f"❌ Element not found: {by}={value}")
        raise


def wait_for_clickable(driver, by, value, timeout=EXPLICIT_WAIT):
    """Wait for element to be clickable and return it."""
    try:
        element = WebDriverWait(driver, timeout).until(
            EC.element_to_be_clickable((by, value))
        )
        return element
    except Exception as e:
        logger.error(f"❌ Element not clickable: {by}={value}")
        raise


# ==================== Test Case ====================

def test_discount_code_application():
    """
    Test Case: Apply SAVE15 Discount Code

    Steps:
    1. Navigate to checkout page
    2. Verify discount code field is present
    3. Enter discount code SAVE15
    4. Click Apply button
    5. Verify discount is applied
    6. Verify total is updated
    """
    driver = None

    try:
        # Setup
        logger.info("=" * 60)
        logger.info(f"Starting Test: {TEST_ID}")
        logger.info("=" * 60)

        driver = setup_driver()

        # Step 1: Navigate to checkout page
        logger.info("Step 1: Navigating to checkout page...")
        driver.get(TEST_URL)
        logger.info(f"✅ Loaded URL: {TEST_URL}")

        # Step 2: Verify discount code field is present
        logger.info("Step 2: Verifying discount code field...")
        discount_field = wait_for_element(driver, By.ID, "discount-code")
        assert discount_field.is_displayed(), "Discount field not visible"
        logger.info("✅ Discount code field found")

        # Step 3: Enter discount code SAVE15
        logger.info("Step 3: Entering discount code SAVE15...")
        discount_field.clear()
        discount_field.send_keys("SAVE15")
        logger.info("✅ Discount code entered")

        # Step 4: Click Apply button
        logger.info("Step 4: Clicking Apply button...")
        apply_button = wait_for_clickable(driver, By.ID, "apply-discount")
        apply_button.click()
        logger.info("✅ Apply button clicked")

        # Wait for discount to be applied
        time.sleep(1)

        # Step 5: Verify discount is applied
        logger.info("Step 5: Verifying discount is applied...")
        discount_amount = wait_for_element(driver, By.ID, "discount-amount")
        discount_text = discount_amount.text

        assert discount_text != "$0.00", "Discount was not applied"
        logger.info(f"✅ Discount applied: {discount_text}")

        # Step 6: Verify total is updated
        logger.info("Step 6: Verifying total is updated...")
        total_element = wait_for_element(driver, By.ID, "total")
        total_text = total_element.text
        logger.info(f"✅ Total updated: {total_text}")

        # Test passed
        logger.info("=" * 60)
        logger.info("✅ TEST PASSED")
        logger.info("=" * 60)

        return True

    except AssertionError as e:
        logger.error(f"❌ Assertion failed: {e}")
        if driver:
            screenshot_path = f"error_{TEST_ID}_{int(time.time())}.png"
            driver.save_screenshot(screenshot_path)
            logger.error(f"Screenshot saved: {screenshot_path}")
        return False

    except Exception as e:
        logger.error(f"❌ Test failed with error: {e}")
        if driver:
            screenshot_path = f"error_{TEST_ID}_{int(time.time())}.png"
            driver.save_screenshot(screenshot_path)
            logger.error(f"Screenshot saved: {screenshot_path}")
        return False

    finally:
        # Cleanup
        if driver:
            logger.info("Closing browser...")
            driver.quit()


# ==================== Main ====================

if __name__ == "__main__":
    success = test_discount_code_application()
    sys.exit(0 if success else 1)
